"""Aggregate compat_probe.py JSON results into docs/compatibility.md.

Run from the repo root: uv run python scripts/compat_report.py <results-dir>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Endpoints that cannot run in public CI: verified by hand, provenance dated.
MANUAL_ROWS = [
    {
        "backend": "AWS S3",
        "version": "(service)",
        "verdict": "enforce",
        "tested_at": "2024-11-25",
        "provenance": "AWS launch announcement + delta-rs production use",
    },
    {
        "backend": "iDrive E2",
        "version": "(service)",
        "verdict": "enforce",
        "tested_at": "2026-07-05",
        "provenance": "manual probe (undocumented by iDrive; verified empirically)",
    },
]

VERDICT_LABEL = {
    "enforce": "✅ enforces",
    "ignore": "❌ accepts but IGNORES — unsafe, corrupts silently",
    "mixed": "⚠️ partial — unsafe",
    "broken": "⚠️ probe failed",
}


def main() -> int:
    """Render the table from a directory of probe JSON files."""
    results_dir = Path(sys.argv[1])
    rows: list[dict[str, str]] = [
        json.loads(p.read_text()) for p in sorted(results_dir.glob("*.json"))
    ]  # pyright: ignore[reportAny]  # probe JSON is our own fixed schema
    rows += MANUAL_ROWS  # pyright: ignore[reportArgumentType]

    lines = [
        "# S3 conditional-write compatibility",
        "",
        "Whether each store **enforces** `If-None-Match: *` / `If-Match: <etag>`",
        "on PUT — the primitive this library's commit protocol rests on. A store",
        "that accepts-but-ignores these headers corrupts a lake with zero errors.",
        "",
        "Rows marked `ci` are re-verified automatically (weekly + on every",
        "version bump via Renovate); a behavior change fails CI on exactly the",
        "version that changed it. Generated by `scripts/compat_report.py` —",
        "do not edit by hand.",
        "",
        "| Backend | Version | Conditional writes | Last verified | Provenance |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['backend']} | `{r['version']}` | {VERDICT_LABEL[r['verdict']]} "
            f"| {r['tested_at']} | {r['provenance']} |"
        )
    lines += [
        "",
        "Probe details: four conditional PUTs per backend "
        "(`scripts/compat_probe.py`); `verify_conditional_writes()` in the",
        "library runs the same check against any endpoint before trusting it.",
        "",
    ]
    Path("docs").mkdir(exist_ok=True)
    Path("docs/compatibility.md").write_text("\n".join(lines))
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
